### ISSUE TITLE
webrtc这个是不是只能localhost下用？

### ISSUE THREAD

**Issue by liping17** [Monibuca/plugin-webrtc#1]
![image](https://user-images.githubusercontent.com/46994788/87266083-f171fe00-c4f6-11ea-8b3e-9c73768104aa.png)

**Comment by langhuihui** [comment]
域名下需要https才行，这是webrtc的规定



---原始邮件---
发件人: "liping17"<notifications@github.com&gt;
发送时间: 2020年7月13日(周一) 上午10:53
收件人: "Monibuca/plugin-webrtc"<plugin-webrtc@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Monibuca/plugin-webrtc] webrtc这个是不是只能localhost下用？ (#1)
