### ISSUE TITLE
使用webrtc播放无声音，使用http-flv播放有声音

### ISSUE THREAD

**Issue by BySlin** [Monibuca/plugin-webrtc#18]
使用系统自带的http://127.0.0.1:8080/preview/live/output1?type=rtc   webrtc方式播放时无声音
使用http://127.0.0.1:8080/preview/live/output1  http-flv播放有声音

webrtc方式现在是否 支持声音播放？

**Comment by langhuihui** [comment]
支持声音播放的，但是不支持AAC格式的声音，只能支持pcma和pcmu格式
