### ISSUE TITLE
WebRtc  播放失败！

### ISSUE THREAD

**Issue by hessonsu** [Monibuca/plugin-webrtc#27]
M7S放在内网，coturn ICE服务器部署在外网。
摄像头同M7S媒体流在公司内网。
在家里（另外一个局域网）使用[subscribe.html](https://github.com/Monibuca/plugin-webrtc/blob/v4/subscribe.html)播放不了视频。
如果在公司是可以使用subscribe.html 可以播放的。
请问可以从那些方面排查问题呢？
![企业微信截图_16975314256760](https://github.com/Monibuca/plugin-webrtc/assets/16568034/4fc67da9-4223-4457-a013-7a23d493f2cb)

**Comment by langhuihui** [comment]
webtc 由于端口问题，如果内网有端口转发，则无法使用

**Comment by hessonsu** [comment]
![image](https://github.com/Monibuca/plugin-webrtc/assets/16568034/412d64ff-9799-46ca-8446-651624b8c3ed)
@langhuihui 从此图上面看。理论上来说。P2P失败。则使用turn协议。由服务器中转流量。不是如此嘛？

**Comment by langhuihui** [comment]
服务器并没有实现 stun 和 turn 功能，如果你需要使用可以自行配置

**Comment by hessonsu** [comment]
@langhuihui  [plugin-webrtc](https://github.com/Monibuca/plugin-webrtc) 应该是客户端，stun 跟turn 是Ice服务实现的(也就是[coturn](https://github.com/coturn/coturn))

**Comment by langhuihui** [comment]
你说的没错

**Comment by hessonsu** [comment]
@langhuihui 我查找了一天了。
好像似乎是由于answer 创建的不一样导致的。
```[plugin-webrtc](https://github.com/Monibuca/plugin-webrtc)
func (IO *WebRTCIO) GetAnswer() (string, error) {
	// Sets the LocalDescription, and starts our UDP listeners
	answer, err := IO.CreateAnswer(nil)
	if err != nil {
		return "", err
	}
	// IO.LocalSDP, err = answer.Unmarshal()
	// if err != nil {
	// 	return "", err
	// }
	gatherComplete := GatheringCompletePromise(IO.PeerConnection)
	if err := IO.SetLocalDescription(answer); err != nil {
		return "", err
	}
	<-gatherComplete
	return IO.LocalDescription().SDP, nil
}

```
而我找到的
链接在 https://github.com/pion/webrtc/blob/master/examples/data-channels/main.go
```golang
// Create an answer
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}
```
我用https://github.com/pion/webrtc/blob/master/examples/data-channels 在我家里跟我公司的能进行通讯了。证明coturn 是部署无问题的

**Comment by hessonsu** [comment]
等我测试

**Comment by hessonsu** [comment]
已经解决
1.双方交换offer,answer
2,交换candidate

**Comment by hessonsu** [comment]
已经解决
1.双方交换offer,answer
2,交换candidate
